# Data paths
data:
  train_annotations: data/train/_annotations_train.coco.json
  valid_annotations: data/valid/_annotations_valid.coco.json
  test_annotations: data/test/_annotations_test.coco.json
  train_images: data/train/img
  valid_images: data/valid/img
  test_images: data/test/img

# Model architecture
model:
  backbone: ResNet50  # or VGG16, ResNet50, etc.
  num_classes: 4  # including background

# Hyperparameters
hyperparameters:
  learning_rate: 0.0001
  batch_size: 5
  epochs: 20
  momentum: 0.9
  weight_decay: 0.0005

# Save model
save_model_path: "model/rcnn_model.pth"